### PR TITLE
Add Dangerfile

### PR DESCRIPTION
**Pull request by rohit-gohri**
- add dangerfile
- add step to build workflow

### CODE REVIEW

**Comment by rohit-drone** [comment]
### TODOs/FIXMEs:
- ``// TODO: Set options for todos`` : [dangerfile.ts](https://github.com/rohit-gohri/danger-plugin-todos/blob/0f19297c38e98af47d03fee421fc342ca3759b8c/dangerfile.ts)
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6de6745690036f3f921f3de4143ddff021bada60
</p>

**Comment by rohit-drone** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>test</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 166c988f3510d8e9f199215f7e17f7f5790efb7b
</p>

**Comment by rohit-drone** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>test</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4268d214a323660596a44b06e61ed3ec0ee33c60
</p>

**Comment by rohit-gohri** [comment]
test

**Pull request merged**
